### ISSUE TITLE
Running stuart_ci_build outside of edk2 tree deletes lots of files

### ISSUE THREAD

**Issue by bcran** [tianocore/edk2-pytool-extensions#231] opened 2020-12-03 22:05 UTC
[CI_BUILDLOG.txt](https://github.com/tianocore/edk2-pytool-extensions/files/5639318/CI_BUILDLOG.txt)
**Describe the bug**
I noticed that running
stuart_ci_build outside of the edk2 tree causes it to delete a lot of files:

I ran the following from one directory above edk2:
```
export WORKSPACE=$PWD
export PACKAGES_PATH=$PWD/edk2:$PWD/edk2-platforms:$PWD/edk2-non-osi
export GCC5_AARCH64_PREFIX=/home/rebecca/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-
. ./edk2/edksetup.sh
~/.local/bin/stuart_ci_build -c edk2/.pytool/CISettings.py
TOOL_CHAIN_TAG=GCC5
```
The output (truncated) includes:
```
WARNING - Allowing Override for key TARGET_ARCH
PROGRESS - Start time: 2020-12-03 15:00:18.874073
PROGRESS - Setting up the Environment
PROGRESS - Running Pre Build
PROGRESS - Running Build NOOPT
ERROR - Build.py #000 from /home/rebecca/src/uefi/edk2/MdeModulePkg/MdeModulePkg.dec(28):   File/directory not found in workspace
CRITICAL - Build failed
PROGRESS - End time: 2020-12-03 15:00:19.705859  Total time Elapsed: 0:00:00
ERROR - --->Test Failed: Host Unit Test Compiler Plugin NOOPT returned 1
PROGRESS - --Running MdeModulePkg: Host Unit Test Dsc Complete Check Test NO-TARGET --
PROGRESS - --->Test Success: Host Unit Test Dsc Complete Check Test NO-TARGET
SECTION - Building NetworkPkg Package
PROGRESS - --Running NetworkPkg: Char Encoding Check Test NO-TARGET --
PROGRESS - --->Test Success: Char Encoding Check Test NO-TARGET
PROGRESS - --Running NetworkPkg: Compiler Plugin DEBUG --
PROGRESS - Start time: 2020-12-03 15:00:19.959846
PROGRESS - Setting up the Environment
PROGRESS - Running Pre Build
PROGRESS - Running Build DEBUG
ERROR - Build.py #000 from /home/rebecca/src/uefi/edk2/MdeModulePkg/MdeModulePkg.dec(28):   File/directory not found in workspace
CRITICAL - Build failed
PROGRESS - End time: 2020-12-03 15:00:21.610770  Total time Elapsed: 0:00:01
ERROR - --->Test Failed: Compiler Plugin DEBUG returned 1
PROGRESS - --Running NetworkPkg: Compiler Plugin RELEASE --
PROGRESS - Start time: 2020-12-03 15:00:21.628725
PROGRESS - Setting up the Environment
PROGRESS - Running Pre Build
PROGRESS - Running Build RELEASE
ERROR - Build.py #000 from /home/rebecca/src/uefi/edk2/MdeModulePkg/MdeModulePkg.dec(28):   File/directory not found in workspace
CRITICAL - Build failed
PROGRESS - End time: 2020-12-03 15:00:23.256355  Total time Elapsed: 0:00:01
ERROR - --->Test Failed: Compiler Plugin RELEASE returned 1
```

And afterwards, "git status" reported:
```
Changes not staged for commit:
   (use "git add/rm <file>..." to update what will be committed)
   (use "git restore <file>..." to discard changes in working directory)
         modified:   BaseTools/Source/Python/Ecc/exception.xml
         deleted:
CryptoPkg/Library/BaseCryptLib/SysCall/UnitTestHostCrtWrapper.c
         deleted:    CryptoPkg/Library/OpensslLib/openssl
         deleted:    CryptoPkg/Library/OpensslLib/rand_pool.c
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/AuthenticodeTests.c
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/BaseCryptLibUnitTests.c
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/BlockCipherTests.c
         deleted: CryptoPkg/Test/UnitTest/Library/BaseCryptLib/DhTests.c
         deleted: CryptoPkg/Test/UnitTest/Library/BaseCryptLib/HashTests.c
         deleted: CryptoPkg/Test/UnitTest/Library/BaseCryptLib/HmacTests.c
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/OaepEncryptTests.c
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/Pkcs5Pbkdf2Tests.c
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/Pkcs7EkuTestSignatures.h
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/Pkcs7EkuTests.c
         deleted: CryptoPkg/Test/UnitTest/Library/BaseCryptLib/RandTests.c
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/RsaPkcs7Tests.c
         deleted: CryptoPkg/Test/UnitTest/Library/BaseCryptLib/RsaTests.c
         deleted: CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TSTests.c
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLib.h
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLibHost.inf
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestBaseCryptLibShell.inf
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestEKUCerts/ChainCreationInstructions.txt
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestEKUCerts/CreateTestCerts.cmd
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestEKUCerts/SignFirmwareWithEKUs.cmd
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestEKUCerts/TestEKUParsingIssuingCA.ini
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestEKUCerts/TestEKUParsingLeafSigner.ini
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestEKUCerts/TestEKUParsingLeafSignerPid1.ini
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestEKUCerts/TestEKUParsingLeafSignerPid12345.ini
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestEKUCerts/TestEKUParsingNoEKUsInSigner.ini
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestEKUCerts/TestEKUParsingPolicyCA.ini
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/TestEKUCerts/TestEKUParsingRoot.ini
         deleted:
CryptoPkg/Test/UnitTest/Library/BaseCryptLib/UnitTestMain.c
         deleted: MdeModulePkg/Library/BrotliCustomDecompressLib/brotli
         deleted: MdeModulePkg/Universal/RegularExpressionDxe/oniguruma
         deleted:    UnitTestFrameworkPkg/Library/CmockaLib/cmocka
```

I also got build errors such as:
```
ERROR - Build.py #000 from
/home/rebecca/src/uefi/edk2/CryptoPkg/Test/CryptoPkgHostUnitTest.dsc(35):
File/directory not found in workspace
CRITICAL - Build failed
```

**To Reproduce**
1. git clone https://github.com/tianocore/edk2.git
2. export WORKSPACE=$PWD
3. export PACKAGES_PATH=$PWD/edk2:$PWD/edk2-platforms:$PWD/edk2-non-osi
4. export GCC5_AARCH64_PREFIX=/home/rebecca/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-
5. . ./edk2/edksetup.sh
6. ~/.local/bin/stuart_ci_build -c edk2/.pytool/CISettings.py TOOL_CHAIN_TAG=GCC5

**Expected behavior**
"git status" ideally should report no files deleted or modified, though I understand BaseTools/Source/Python/Ecc/exception.xml gets modified as part of a normal run.

**Execution environment**
openSUSE Leap 15.2, python 3.6.12, gcc 7.5.0
List the OS, python version, system environment variables, etc.
export WORKSPACE=$PWD
export PACKAGES_PATH=$PWD/edk2:$PWD/edk2-platforms:$PWD/edk2-non-osi
export GCC5_AARCH64_PREFIX=/home/rebecca/gcc-arm-10.2-2020.11-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-

**Pip Packages**
```
Package                Version  
---------------------- ---------
antlr4-python3-runtime 4.7.1    
apparmor               2.13.4   
appdirs                1.4.3    
asn1crypto             0.24.0   
Beaker                 1.11.0   
certifi                2018.1.18
cffi                   1.13.2   
chardet                3.0.4    
Click                  7.0      
cmdln                  2.0.0    
configobj              5.0.6    
createrepo-c           0.15.4   
cryptography           2.8      
cupshelpers            1.0      
Cython                 0.29.14  
decorator              4.2.1    
edk2-pytool-extensions 0.13.10  
edk2-pytool-library    0.10.13  
fido2                  0.5.0    
gitdb2                 2.0.6    
GitPython              3.0.5    
hiredis                1.0.1    
idna                   2.6      
ipaddr                 2.1.11   
isc                    2.0      
LibAppArmor            2.13.4   
libvirt-python         6.0.0    
libxml2-python         2.9.7    
Mako                   1.0.7    
MarkupSafe             1.0      
modernize              0.7      
mysqlclient            1.4.6    
ndg-httpsclient        0.5.1    
netifaces              0.10.6   
nose                   1.3.7    
packaging              20.3     
pexpect                4.8.0    
pip                    10.0.1   
ply                    3.10     
ptyprocess             0.5.2    
py                     1.8.1    
pyasn1                 0.4.2    
pycairo                1.19.1   
pycparser              2.17     
pycryptodome           3.9.0    
pycups                 1.9.74   
pycurl                 7.43.0.2 
pyelftools             0.26     
Pygments               2.2.0    
PyGObject              3.34.0   
pylibmc                1.6.1    
pymongo                3.6.0    
pyOpenSSL              17.5.0   
pyparsing              2.2.0    
pyscard                1.9.6    
PySocks                1.6.8    
python-evtx            0.5.3    
python-gitlab          1.11.0   
python-linux-procfs    0.6      
python-memcached       1.58     
pyudev                 0.21.0   
pyusb                  1.0.2    
PyYAML                 5.3.1    
redis                  3.4.1    
requests               2.20.1   
rpm                    4.14.1   
setuptools             40.5.0   
six                    1.14.0   
slip                   0.6.5    
slip.dbus              0.6.5    
smmap2                 2.0.5    
SQLAlchemy             1.2.14   
urllib3                1.24     
urlscan                0.9.2    
urwid                  2.0.1    
wrapt                  1.10.10  
yubikey-manager        2.1.0    
You are using pip version 10.0.1, however version 20.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Additional context**

**Comment by spbrogan** [comment] 2020-12-04 04:17
i am trying to read between the lines on your steps to reproduce. 

I assume you called `~/.local/bin/stuart_update -c edk2/.pytool/CISettings.py` before calling build?
I also assume you build the edk2 base tools binaries (maybe that was part of edk2setup.sh)?

you are following the steps here: https://github.com/tianocore/edk2/blob/master/.pytool/Readme.md#running-ci

Finally, I want to point out a few concerns. 

You are using the edk2 repo ci.  This is for the edk2 repo only.  It will not run CI on non-osi or edk2-platforms.  
The edk2 CI doesn't use the workspace or packages path you have set.   And/or the environment setup in edk2setup.sh. 

Don't do these: 
```
export WORKSPACE=$PWD
export PACKAGES_PATH=$PWD/edk2:$PWD/edk2-platforms:$PWD/edk2-non-osi
. ./edk2/edksetup.sh
```

The path to the workspace is set in the CI file relative to the CI file and thus it doesn't care what your current working directory is.  


In project Mu we have CI for all of our repos. You can see each repo has its own CiSettings.py file which are different based on the packages within the repository.    Here are examples of three repos.  

https://github.com/microsoft/mu_basecore/tree/release/202008/.pytool
https://github.com/microsoft/mu_plus/tree/release/202008/.pytool
https://github.com/microsoft/mu_tiano_plus/tree/release/202008/.pytool


On another path to root cause your issue;  if you deleted these two plugins in your local edk2 repo we can determine that they are responsible for the deletions.  I don't see how it is pytool-extensions that is doing the delete.  
https://github.com/tianocore/edk2/tree/master/.pytool/Plugin/EccCheck
https://github.com/tianocore/edk2/tree/master/.pytool/Plugin/LicenseCheck

I will try to join discord Friday 12/4 as that might be faster to work thru this if that is something you want to do.

**Comment by bcran** [comment] 2020-12-04 04:34
Thanks. I had run stuart_ci_update a few days ago, so didn't think it 
necessary to run it again. Also I'd been building from edk2 so yes I'd 
already built the BaseTools.


I've worked around the problem by running the following in my testing 
script:

unset WORKSPACE
unset PACKAGES_PATH
unset EDK_TOOLS_PATH
unset CONF_PATH
cd ../../../edk2
. ./edksetup.sh
~/.local/bin/stuart_ci_build -c .pytool/CISettings.py 
TOOL_CHAIN_TAG=GCC5 -a X64,AARCH64,RISCV64,IA32 -t 
NO-TARGET,NOOPT,DEBUG,RELEASE


That way, no files are modified or deleted.

It sounds like the way I was running it isn't supported, so feel free to 
close the issue I opened earlier today.


-- 
Rebecca Cran

**Comment by spbrogan** [comment] 2020-12-04 18:06
Will close this here. 

My hunch and i have no plans to spend more time to root cause is that the EccCheck tool which runs git commands and is known to "clean" a workspace is somehow getting confused with the environment.  Given that EccCheck is part of edk2 and not pytools it makes more sense to track issues in their bugzilla.   Thanks.

**Closed by spbrogan** 2020-12-04 18:06 UTC
Labels: wontfix
