### ISSUE TITLE
[Feature]: stuart_update and stuart_build shouldn't delete external dependencies and allow a change to build

### ISSUE THREAD

**Issue by Flickdm** [tianocore/edk2-pytool-extensions#336] opened 2022-11-04 18:58 UTC
### What does the feature solve?

In reference to [Issue 335](https://github.com/tianocore/edk2-pytool-extensions/issues/335)
stuart_update currently deletes changes to source external dependencies.

### Describe the solution

Determine if a repo is 'dirty' or if changes were made and if changes were made warn a user but allow the code to build

**Comment by Javagedes** [comment] 2022-11-08 19:05
Confirmed stuart_update does delete a dirty git_extdep. This is due to the fact that the sde calls clean() on any dependency that is dirty. clean() ends up calling a RemoveTree() on the dependency.

Possible solutions:
1. Change Verify() for a git_extdep to only return false if it has not been initialized. This allows git dependencies to be dirty or on a different commit. This aligns git dependencies with submodules.
2. Change the Clean() method check if their is un-commented code before calling RemoveTree. If there is, set the error_msg warning the user and raise a RuntimeError. This will log the error message and cause the update to fail. We could optionally add a --Force flag to stuart_update that will forcefully delete the dependency anyway, and we can add that as a part of the error message. Something like `self.error_msg = f'{self.name} external dependency has uncommented changes. Either commit these changes or run the command again with the --Force flag'

Confirmed stuart_build prevents building with a dirty git_extdep as it verifies each dependency at the start of the command.

Possible solutions:
1. If we take change 1 for the first issue, then no additional change is needed as we will pass the verify() check here.
2. Add a SKIPVERIFY command line option to uefi_build. Then in edk2_platform_build, override the GetVerifyCheckRequired() method to check the value of the flag (`return not self.PlatformBuilder.SkipVerify`).

**Comment by Javagedes** [comment] 2022-11-08 22:35
Talking with Doug, another option if we wish to make zero changes, is that we need to update docs/features/feature_extdep.md to explain the best approach if a change in an extdep needs to be made.

I think the best approach would be to fork the repo, make the changes you need, and submit a PR. Then in the meantime, just change the yaml file for the expdep to point at the forked repo (until the PR has been merged).

**Comment by spbrogan** [comment] 2022-11-12 06:03
this is by design and I don't think I would vote to change it.  
see last sentence here: https://github.com/tianocore/edk2-pytool-extensions/blob/master/docs/usability/using_extdep.md#git-dependency

But in short the reason you make something in ext_dep rather than submodule or some other method of sharing source is because you want strong traceability and to treat it as read only.  If you allow dirty repos then that is lost.  I also don't think it is worth trying to save a users work because that is hard to do right for all cases and it encourages using ext_deps for non static work.

**Comment by Javagedes** [comment] 2022-12-15 22:36
Closing per conversation

**Closed by Javagedes** 2022-12-15 22:36 UTC
Labels: enhancement, new, discussion
