### ISSUE TITLE
[Feature]: Allow extdep to use local resource for co-development

### ISSUE THREAD

**Issue by cfernald** [tianocore/edk2-pytool-extensions#415] opened 2023-01-25 19:39 UTC
### What does the feature solve?

When using extdep for a co-developed component such as in a git or nuget extdep. Currently, you can overrite the location using a build environment variable, but this does not work for build plugins or other self-describing environment components. 

### Describe the solution

Add a option similar to "pip install -e" that allows an extdep to symlink to a local copy of the resource to support co-development. This should be saved into the state file so that the pre-build check also knows to ignore the version or dirty state checks. This could be done by running a standalone command or adding flag options to stuart_update.

### Additional context

This is part of an effort Project MU is trying to create more stand-alone feature repos that can be consumed not as a submodule but as a complete package either through nuget or a git extdep. This is used for the following repos.

https://github.com/microsoft/mu_feature_ipmi
https://github.com/microsoft/mu_feature_mm_supv
https://github.com/microsoft/mu_feature_config

**Comment by Javagedes** [comment] 2023-01-25 20:19
Duplicate of #394 however your description better describes the issue, so I'll close it in preference to your issue.

@cfernald Just to clarify, the main issue you're having is that when you override the path to the feature repo to a local copy, no plugins, ext_deps, and path_envs from that repo are found, correct? I've thought about this and I think one of the simpler solutions is to have the self describing environment scan package paths if they are outside of the workspace.

**Comment by cfernald** [comment] 2023-01-25 20:38
@Javagedes, yes pretty much. More generically we need a better solution for co-developing on an extdep that will ensure its use in all directory/package walks. Whether this remains as a build environment variable override or a new mechanism I'm open to. I do fear if we tack more on to just relying on the packages path, and by extension the build environment variables, this may cause some brittleness as people may write plugins that don't properly follow this dependency. I wonder if just breaking for the path searching and building a way for extdeps to symlink may prevent that. I'll defer to your expertise here though.

@spbrogan @kuqin12 have been plugged into this conversation as well.

**Comment by Javagedes** [comment] 2023-01-26 18:44
@cfernald you should be able to symlink the path yourself already. I'm fairly certain path resolution in stuart handles symlinks.

**Comment by Javagedes** [comment] 2023-01-26 19:17
It does not work perfectly due to verifying extdep state failing for different commit versions.

**Comment by cfernald** [comment] 2023-01-26 21:02
yeah, I was curious about that but didnt get around to testing it yet. I really think if we want to support this flow we should build a mechanism into the tooling itself or there will be too many ways people will hack it up or misuse it.

**Comment by Javagedes** [comment] 2023-01-27 17:28
@cfernald  #419 is up for you to test. This update allows you to build a platform with local changes to an external dependency. It enables you to co-develop straight in the parent repo, but if you wish, you could also symlink your repo into the parent repo (if you were say, wanting to test your change against multiple platforms without needing to keep everything in sync).

Be warned, do not call stuart_update once you start co-developing; it will erase and redownload your repo. It's still up in the air if we want to change this logic or not.

**Closed** 2023-01-30 19:08 UTC
Labels: enhancement, new
